### ISSUE TITLE
Strict requirement on protobuf/toml versions?

### ISSUE THREAD

**Issue by matthiasdiener** [P403n1x87/austin-python#17]
### Description

This came up in https://github.com/conda-forge/austin-python-feedstock/pull/13 . Currently, `austin-python` has quite strict requirements on the versions of the `protobuf` and `toml` packages (from `pyproject.toml`):

```
  "protobuf~=3.12.2",
  [...]
  "toml~=0.10.2",
```

Are these versions required, or can we use newer versions of `protobuf` and `toml`?

### Steps to Reproduce

n/a

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

1.5.0

### Additional Information

n/a

**Comment by P403n1x87** [comment]
Thanks for reporting this @matthiasdiener . This is an interesting question. For `toml` I believe we can relax the pin, to the point where we can remove it entirely starting with 3.11. The protobuf dependency is only really needed for the tool that comes with the library, so that could be pushed into extras perhaps.
